[project]
dependencies = [
    "overture-schema-core",
    "overture-schema-places-theme",
    "pydantic>=2.0",
]
description = "Overture Maps places extended with operating hours support"
dynamic = ["version"]
license = "MIT"
name = "overture-schema-extensions"
readme = "README.md"
requires-python = ">=3.10"

[tool.uv.sources]
overture-schema-core = { workspace = true }
overture-schema-places-theme = { workspace = true }

[build-system]
build-backend = "hatchling.build"
requires = ["hatchling"]

[tool.hatch.version]
path = "src/overture/schema/extensions/__about__.py"

[tool.hatch.build.targets.wheel]
packages = ["src/overture"]

[project.entry-points."overture.models"]
"extensions.entity_with_operating_hours" = "overture.schema.extensions:EntityWithOperatingHours"
"extensions.place_with_operating_hours" = "overture.schema.extensions:PlaceWithOperatingHours"
