[project]
dependencies = [
    "overture-schema-core",
    "pydantic>=2.0",
]
description = "Overture Maps transportation theme with shared structures and connector and segment types"
dynamic = ["version"]
license = "MIT"
name = "overture-schema-transportation-theme"
readme = "README.md"
requires-python = ">=3.10"

[tool.uv.sources]
overture-schema-core = { workspace = true }


[build-system]
build-backend = "hatchling.build"
requires = ["hatchling"]

[tool.hatch.version]
path = "src/overture/schema/transportation/__about__.py"

[tool.hatch.build.targets.wheel]
packages = ["src/overture"]

[project.entry-points."overture.models"]
"overture:transportation:connector" = "overture.schema.transportation:Connector"
"overture:transportation:segment" = "overture.schema.transportation:Segment"
