[project]
name = "overture-schema-sources"
dynamic = ["version"]
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
license = "MIT"
dependencies = [
    "overture-schema-core",
    "pydantic>=2.0",
]

[tool.uv.sources]
overture-schema-core = { workspace = true }

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[dependency-groups]
dev = [
    "pytest>=7.0",
    "ruff",
    "mypy",
]

[tool.hatch.version]
path = "src/overture/schema/__about__.py"

[tool.hatch.build.targets.wheel]
packages = ["src/overture"]

[project.entry-points."overture.models"]
"sources.sources" = "overture.schema.sources.models:Sources"

[tool.pytest.ini_options]
pythonpath = ["src"]
testpaths = ["tests"]
