[project]
dependencies = [
    "overture-schema-core",
    "pydantic>=2.0",
]
description = "Overture Maps addresses theme models and structures"
dynamic = ["version"]
license = "MIT"
name = "overture-schema-addresses-theme"
readme = "README.md"
requires-python = ">=3.10"

[tool.uv.sources]
overture-schema-core = { workspace = true }


[build-system]
build-backend = "hatchling.build"
requires = ["hatchling"]

[tool.hatch.version]
path = "src/overture/schema/addresses/__about__.py"

[tool.hatch.build.targets.wheel]
packages = ["src/overture"]

[tool.pytest.ini_options]
pythonpath = ["src"]
testpaths = ["tests"]

[project.entry-points."overture.models"]
"addresses.address" = "overture.schema.addresses.address.models:Address"
